<a href="https://colab.research.google.com/github/RollingThunder-B/DT_academy_edu_B/blob/master/S1_Day3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
x = range(10)
print(x)

range(0, 10)


In [4]:
for i in x :
  print (i*i)

0
1
4
9
16
25
36
49
64
81


In [13]:
y = np.arange(12)
print(y)
type(y)
len(y)
y.shape

[ 0  1  2  3  4  5  6  7  8  9 10 11]


(12,)

In [17]:

z = y.reshape(3,4)
z

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [22]:
z = y.reshape(-1,2)   # 앞에 -1 을 쓰면 뒤에꺼에 알아서 맞춰줌
z

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [19]:
z = y.reshape(3, 2, 2)
z

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [23]:
!ls

sample_data


In [24]:
!pwd

/content
